#!/bin/sh
# embed.sh -- turn every file in DIR into one C source (web.c): a table of
# name, content type and bytes, so the binary carries its own web page and
# icons. POSIX sh + od, no xxd. Regenerated by make when web/ changes.
#
#   sh embed.sh ../web > web.c

DIR=$1
[ -d "$DIR" ] || { echo "usage: $0 DIR" >&2; exit 2; }

ctype() {
	case $1 in
	*.html) echo text/html ;;
	*.css)  echo text/css ;;
	*.js)   echo text/javascript ;;
	*.gif)  echo image/gif ;;
	*.png)  echo image/png ;;
	*.svg)  echo image/svg+xml ;;
	*)      echo application/octet-stream ;;
	esac
}

echo "/* web.c -- GENERATED by embed.sh from web/; do not edit. */"
echo "#include <stddef.h>"
echo "#include \"web.h\""
i=0
for f in "$DIR"/*; do
	[ -f "$f" ] || continue
	i=$((i+1))
	echo "static const unsigned char a$i[] = {"
	od -An -v -tx1 "$f" | sed 's/ *\([0-9a-f][0-9a-f]\)/0x\1,/g'
	echo "0 };"
done
echo "const struct gc_asset gc_assets[] = {"
i=0
for f in "$DIR"/*; do
	[ -f "$f" ] || continue
	i=$((i+1))
	echo "    { \"$(basename "$f")\", \"$(ctype "$f")\", a$i, sizeof a$i - 1 },"
done
echo "};"
echo "const size_t gc_assets_n = sizeof gc_assets / sizeof gc_assets[0];"
